return function(glove)
	local ReplicatedStorage = game:GetService("ReplicatedStorage")
	local FindGlove = game.FindFirstChild
	local lookup = {
		["Default"] = FindGlove(ReplicatedStorage, "b"),
		["Extended"] = FindGlove(ReplicatedStorage, "b"),
		----------------------------------------
		["Diamond"] = FindGlove(ReplicatedStorage, "DiamondHit"),
		["ZZZZZZZ"] = FindGlove(ReplicatedStorage, "ZZZZZZZHit"),
		["Brick"] = FindGlove(ReplicatedStorage, "BrickHit"),
		["Snow"] = FindGlove(ReplicatedStorage, "SnowHit"),
		["Pull"] = FindGlove(ReplicatedStorage, "PullHit"),
		["Flash"] = FindGlove(ReplicatedStorage, "FlashHit"),
		["Spring"] = FindGlove(ReplicatedStorage, "springhit"),
		["Swapper"] = FindGlove(ReplicatedStorage, "HitSwapper"),
		["Bull"] = FindGlove(ReplicatedStorage, "BullHit"),
		["Dice"] = FindGlove(ReplicatedStorage, "DiceHit"),
		["Ghost"] = FindGlove(ReplicatedStorage, "GhostHit"),
		["Thanos"] = FindGlove(ReplicatedStorage, "ThanosHit"),
		["Stun"] = FindGlove(ReplicatedStorage, "HtStun"),
		["Za Hando"] = FindGlove(ReplicatedStorage, "zhramt"),
		["Fort"] = FindGlove(ReplicatedStorage, "Fort"),
		["Magnet"] = FindGlove(ReplicatedStorage, "MagnetHIT"),
		["Pusher"] = FindGlove(ReplicatedStorage, "PusherHit"),
		["Anchor"] = FindGlove(ReplicatedStorage, "hitAnchor"),
		["Space"] = FindGlove(ReplicatedStorage, "HtSpace"),
		["Boomerang"] = FindGlove(ReplicatedStorage, "BoomerangH"),
		["Speedrun"] = FindGlove(ReplicatedStorage, "Speedrunhit"),
		["Mail"] = FindGlove(ReplicatedStorage, "MailHit"),
		["Golden"] = FindGlove(ReplicatedStorage, "GoldenHit"),
		["Reaper"] = FindGlove(ReplicatedStorage, "ReaperHit"),
		["Defense"] = FindGlove(ReplicatedStorage, "DefenseHit"),
		["Killstreak"] = FindGlove(ReplicatedStorage, "KSHit"),
		["Reverse"] = FindGlove(ReplicatedStorage, "ReverseHit"),
		["Shukuchi"] = FindGlove(ReplicatedStorage, "ShukuchiHit"),
		["Duelist"] = FindGlove(ReplicatedStorage, "DuelistHit"),
		["Woah"] = FindGlove(ReplicatedStorage, "woahHit"),
		["Ice"] = FindGlove(ReplicatedStorage, "IceHit"),
		["Adios"] = FindGlove(ReplicatedStorage, "hitAdios"),
		["Blocked"] = FindGlove(ReplicatedStorage, "BlockedHit"),
		["Engineer"] = FindGlove(ReplicatedStorage, "engiehit"),
		["Rocky"] = FindGlove(ReplicatedStorage, "RockyHit"),
		["Conveyor"] = FindGlove(ReplicatedStorage, "ConvHit"),
		["STOP"] = FindGlove(ReplicatedStorage, "STOP"),
		["Custom"] = FindGlove(ReplicatedStorage, "CustomHit"),
		["Phantom"] = FindGlove(ReplicatedStorage, "PhantomHit"),
		["Wormhole"] = FindGlove(ReplicatedStorage, "WormHit"),
		["Acrobat"] = FindGlove(ReplicatedStorage, "AcHit"),
		["Plague"] = FindGlove(ReplicatedStorage, "PlagueHit"),
		["Megarock"] = FindGlove(ReplicatedStorage, "DiamondHit"),
		["[REDACTED]"] = FindGlove(ReplicatedStorage, "ReHit"),
		["bus"] = FindGlove(ReplicatedStorage, "hitbus"),
		["Phase"] = FindGlove(ReplicatedStorage, "PhaseH"),
		["Warp"] = FindGlove(ReplicatedStorage, "WarpHt"),
		["Bomb"] = FindGlove(ReplicatedStorage, "BombHit"),
		["Bubble"] = FindGlove(ReplicatedStorage, "BubbleHit"),
		["Jet"] = FindGlove(ReplicatedStorage, "JetHit"),
		["Shard"] = FindGlove(ReplicatedStorage, "ShardHIT"),
		["potato"] = FindGlove(ReplicatedStorage, "potatohit"),
		["Cult"] = FindGlove(ReplicatedStorage, "CULTHit"),
		["bob"] = FindGlove(ReplicatedStorage, "bobhit"),
		["Buddies"] = FindGlove(ReplicatedStorage, "buddiesHIT"),
		["Moon"] = FindGlove(ReplicatedStorage, "CelestialHit"),
		["Jupiter"] = FindGlove(ReplicatedStorage, "CelestialHit"),
		["Spy"] = FindGlove(ReplicatedStorage, "SpyHit"),
		["Detonator"] = FindGlove(ReplicatedStorage, "DetonatorHit"),
		["Rage"] = FindGlove(ReplicatedStorage, "GRRRR"),
		["Trap"] = FindGlove(ReplicatedStorage, "traphi"),
		["Orbit"] = FindGlove(ReplicatedStorage, "Orbihit"),
		["Hybrid"] = FindGlove(ReplicatedStorage, "HybridCLAP"),
		["Slapple"] = FindGlove(ReplicatedStorage, "SlappleHit"),
		["Disarm"] = FindGlove(ReplicatedStorage, "DisarmH"),
		["Dominance"] = FindGlove(ReplicatedStorage, "DominanceHit"),
		["Nightmare"] = FindGlove(ReplicatedStorage, "nightmarehit"),
		["rob"] = FindGlove(ReplicatedStorage, "robhit"),
		["Link"] = FindGlove(ReplicatedStorage, "LinkHit"),
		["Rhythm"] = FindGlove(ReplicatedStorage, "rhythmhit"),
		["Hitman"] = FindGlove(ReplicatedStorage, "HitmanHit"),
		["Rojo"] = FindGlove(ReplicatedStorage, "RojoHit"),
		["Thor"] = FindGlove(ReplicatedStorage, "ThorHit"),
		["Cloud"] = FindGlove(ReplicatedStorage, "CloudHit"),
		["Retro"] = FindGlove(ReplicatedStorage, "RetroHit"),
		["Null"] = FindGlove(ReplicatedStorage, "NullHit"),
		----------------------------------------
		["Mitten"] = FindGlove(ReplicatedStorage, "MittenHit"),
		["Hallow Jack"] = FindGlove(ReplicatedStorage, "HallowHIT"),
		----------------------------------------
		["Boogie"] = FindGlove(ReplicatedStorage, "HtStun"),
		["Balloony"] = FindGlove(ReplicatedStorage, "HtStun"),
		["Kinetic"] = FindGlove(ReplicatedStorage, "HtStun"),
		----------------------------------------
		["OVERKILL"] = FindGlove(ReplicatedStorage, "Overkillhit"),
		["The Flex"] = FindGlove(ReplicatedStorage, "FlexHit"),
		["God's Hand"] = FindGlove(ReplicatedStorage, "Godshand"),
		["Error"] = FindGlove(ReplicatedStorage, "Errorhit")
	}

	if not lookup[glove] then
		return ReplicatedStorage.GeneralHit
	else
		return lookup[glove]
	end
end
